FROM python:3.10-slim-buster

RUN mkdir repo
RUN mkdir repo/root

ADD /front repo/root/front

WORKDIR /repo/root

RUN pip install --upgrade pip
RUN pip install -r ./front/requirements.txt

EXPOSE 8000

CMD ["python", "-u", "./front/main.py"]
