FROM python:3.10-slim-buster

RUN mkdir repo
RUN mkdir repo/root

ADD /bot repo/root/bot


WORKDIR repo/root/bot

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

ENV RSI_API_KEY=
ENV PAIR=
ENV INITIAL_USDT=
ENV INITIAL_CRYPTO=

CMD ["python", "-u", "main.py"]