version: '3'
services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile.bot
    container_name: bot-container
    env_file:
      - .env
    volumes:
      - volcsv:/bot/csv
  front:
    build:
      context: ./
      dockerfile: ./Dockerfile.front # path to dockerfile
    ports: # Port binding to host from docker container
      - "8000:8000" # Bind port 8000 of host to 8000 of container
    container_name: front-container
    volumes:
      - volcsv:/front/csv
volumes:
  volcsv:
